### ISSUE TITLE
CSS: Make the background circles in the list identical.

### ISSUE THREAD

**Issue by its-haanna** [jeffreycharters/station#71]
Hi! The ordered list's background differs depending on the number, which makes it look odd.

![Screen Shot 2022-10-02 at 6 53 30 PM](https://user-images.githubusercontent.com/83631167/193448296-a55c242b-ec48-4d08-82c6-87bc31df5f94.png)

I think it would be good to fix that!

**Comment by michaella23** [comment]
@its-haanna I agree! I've assigned this issue to you. Happy hacking!

**Comment by its-haanna** [comment]
Seems it's been fixed already, was it @ramdhanihendrie? If so I'll close the issue.

**Comment by ramdhanihendrie** [comment]
> Seems it's been fixed already, was it @ramdhanihendrie? If so I'll close the issue.

My PR #80 hasn't been accepted yet

**Comment by michaella23** [comment]
Hello friends. @its-haanna  had created this issue and was assigned to it. I'm trying to think of how we could go forward. @ramdhanihendrie, I haven't merged your PR yet because of this confusion. I don't want anyone to feel discouraged from participating! Anna, had you already worked on this? I'd love to merge your branch if you submit a pull request, and perhaps Hendrie, you could create another issue and work on it. I'm new to both contributing and maintaining a repository, so I am open to feedback and I appreciate your understanding.

**Comment by its-haanna** [comment]
Hey, @michaella23 it's okay, I haven't worked on it since I saw @ramdhanihendrie has done it so it's okay to just merge his PR. :)

**Comment by michaella23** [comment]
@its-haanna , thanks for understanding! I think 4 different people were working on this in their own branches! 😅 I did end up merging @ramdhanihendrie's PR. But I hope you'll feel free to add a new feature or create an issue to fix an existing one. 😊
