### ISSUE TITLE
The circle around the numbering doesn't look right

### ISSUE THREAD

**Issue by Njong392** [jeffreycharters/station#78]
I see that the numbering has circles around them. But the shape of the circles doesn't quite look okay. Think it has something to do with the CSS.

![Screenshot from 2022-10-03 00-04-48](https://user-images.githubusercontent.com/81039882/193480366-71937dd3-cd32-4724-b0c1-f753d5d25c11.png)

**Comment by Atulsoam562003** [comment]
Hello. I can work on this. You can assign it to me if no one has already requested it. Thankyou.

**Comment by jeffreycharters** [comment]
All yours, good luck!

**Comment by michaella23** [comment]
Hello all, this issue is very similar to #71 , which was created early yesterday. @Atulsoam562003 I'm not sure if you've already started working on it? But there are two other contributors who have also been working on this issue in their own branches 😅. I want everyone to be able to contribute, but this duplication has made things a little complicated at the moment! Open to feedback, and appreciate your understanding.

**Comment by Atulsoam562003** [comment]
ok. No problem ✌ @michaella23. 🙂

**Comment by michaella23** [comment]
Closing this issue since it is a duplicate.
